public class RecursiveUtilityClass {
    //Recurcive varible for method on user trigger
    Public static boolean isRecursive_taskCreationForGoals =false;
     //Recurcive varible for method on  Goal Tracking Trigger
    Public static boolean isRecursive_updateTaskForGoalTrackings=false;
     //Recurcive varible for method on GoalResponses trigger
    Public static boolean isRecursive_updateTaskForGoalResponses=false;
}